import fs from "node:fs";
import path from "node:path";
import {execFileSync} from "node:child_process";
import {fileURLToPath} from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const read=file=>fs.readFileSync(path.join(root,file),"utf8");
const json=file=>JSON.parse(read(file));
const release=json("release.json"),manifest=json("manifest.webmanifest");
const version=release.version,cache=release.cache,saveKey=release.saveKey,q=`v=${version}`;
const files={html:read("index.html"),game:read("js/game.js"),main:read("js/main.js"),engine:read("js/engine.js"),sw:read("sw.js"),css:read("styles.css"),readme:read("README.md")};
const errors=[];
const fail=(condition,message)=>{if(!condition)errors.push(message)};
for(const [name,text] of Object.entries(files))fail(text.trim().length>0,`${name} is empty`);
for(const file of ["js/engine.js","js/game.js","js/main.js","sw.js"]){try{execFileSync(process.execPath,["--check",path.join(root,file)],{stdio:"pipe"})}catch(error){errors.push(`${file} syntax: ${(error.stderr||error.message).toString().trim()}`)}}
const ids=[...files.html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
for(const id of new Set(ids))fail(ids.filter(x=>x===id).length===1,`duplicate DOM id: ${id}`);
const refs=[...files.game.matchAll(/\$\("([^"]+)"\)/g)].map(m=>m[1]);
for(const id of new Set(refs))fail(ids.includes(id),`missing DOM id referenced by game: ${id}`);
fail(manifest.name.includes(version),`manifest name does not include ${version}`);
fail(manifest.short_name.includes(version),`manifest short_name does not include ${version}`);
fail(files.html.includes(`content="${version}"`),"HTML build meta mismatch");
fail(files.html.includes(`EVOLVA v${version}`),"HTML visible/title version mismatch");
fail(files.html.includes(`js/main.js?${q}`),"HTML bootstrap query mismatch");
fail(files.main.includes(`engine.js?${q}`)&&files.main.includes(`game.js?${q}`),"module import query mismatch");
fail(files.game.includes(`BUILD_VERSION="${version}"`),"game build constant mismatch");
fail(files.game.includes(`BUILD_CACHE="${cache}"`),"game cache constant mismatch");
fail(files.game.includes(`SAVE_KEY="${saveKey}"`),"game save key mismatch");
fail(files.sw.includes(`CACHE="${cache}"`),"service-worker cache mismatch");
for(const asset of ["styles.css","manifest.webmanifest","js/main.js","js/engine.js","js/game.js"])fail(files.sw.includes(`${asset}?${q}`),`service-worker shell query missing: ${asset}?${q}`);
fail(files.readme.includes(version),"README version mismatch");
fail(files.readme.includes(cache),"README cache mismatch");
fail(!fs.existsSync(path.join(root,"game.js")),"obsolete root game.js still present");
for(const key of ["evolva-save-v8-2-0","evolva-save-v8-1-0","evolva-save-v7-5-1","evolva-save-v7"])fail(files.game.includes(key),`migration key missing: ${key}`);
for(const feature of ["function inspectionTier()","function threatAssessment(o)","capacityEffects(axis)","ATLAS_LOGICAL_W=860","function pointerCancel(e)"])fail(files.game.includes(feature),`feature missing: ${feature}`);
fail(!files.game.includes('pointercancel",pointerEnd'),"pointer cancellation still executes tap action");
fail(files.game.includes("box.hidden=false;\n const rect=atlasCanvas.getBoundingClientRect(),bw=box.offsetWidth"),"Atlas tooltip is not measured before positioning");
if(errors.length){console.error(`EVOLVA ${version} audit failed:\n- ${errors.join("\n- ")}`);process.exit(1)}
console.log(`EVOLVA ${version} release audit passed (${Object.keys(files).length} source files, ${ids.length} DOM ids, ${new Set(refs).size} DOM references).`);
